"""
Lesson 5: Files and error handling.

Use pathlib for readable, cross-platform file path handling.
Use exceptions to handle expected runtime errors safely.
"""

from pathlib import Path


def read_text_file(file_path: Path) -> str:
    """Read and return UTF-8 text from a file."""
    return file_path.read_text(encoding="utf-8")


def write_text_file(file_path: Path, content: str) -> None:
    """Write UTF-8 text to a file."""
    file_path.write_text(content, encoding="utf-8")


def safe_divide(first_number: float, second_number: float) -> float | None:
    """
    Divide two values safely.

    Returns None when division by zero is attempted.
    """
    try:
        return first_number / second_number
    except ZeroDivisionError:
        return None


def main() -> None:
    print("=== Error Handling ===")
    result = safe_divide(10, 0)

    if result is None:
        print("A number cannot be divided by zero.")
    else:
        print(result)

    print("\n=== Reading and Writing Files ===")
    project_root = Path(__file__).resolve().parents[2]
    source_file = project_root / "data" / "sample_notes.txt"
    output_file = project_root / "data" / "generated_notes.txt"

    try:
        notes = read_text_file(source_file)
        print("Contents of sample_notes.txt:")
        print(notes)

        write_text_file(output_file, "This file was generated by lesson 5.\n")
        print(f"Created: {output_file.name}")

    except FileNotFoundError:
        print(f"Could not find the file: {source_file.name}")
    except PermissionError:
        print("Permission was denied while accessing a file.")


if __name__ == "__main__":
    main()
